run:
  tests: true

issues:
  exclude-dirs:
    - bin
    - docs
    - example
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - unused

linters-settings:
  errcheck:
    exclude-functions:
      - fmt:.*
      - "[rR]ead|[wW]rite|[cC]lose"
      - io:Copy

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unused
